<!--
    
    "BECAUSE WE CAN"

    This file is used as a follow-up transformation to macros.xsl to
    correct namespaces in macro expansions.

  -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
		xmlns:extra="http://lichteblau.com/extra"
		version="1.0">
  <xsl:output method="xml" indent="no"/>

  <xsl:template match="@*|node()">
    <xsl:copy>
      <xsl:apply-templates select="@*|node()"/>
    </xsl:copy>
  </xsl:template>

  <xsl:template match="comment()"/>

  <xsl:template match="/">
    <xsl:comment>
      CAREFUL, THIS STYLESHEET IS AUTOGENERATED
    </xsl:comment>
    <xsl:apply-templates/>
  </xsl:template>

  <xsl:template match="extra:*">
    <xsl:element name="xsl:{local-name()}">
      <xsl:apply-templates select="@*|node()"/>
    </xsl:element>
  </xsl:template>
</xsl:stylesheet>
